#! /usr/bin/python

import csv
import sys

print("\\begin{tabular}")

with open(sys.argv[1], "r") as f:
    reader = csv.reader(f)
    rn = 0
    prefix1 = ""
    prefix2 = ""
    category = ""
    type = ""
    nip = 0
    for row in reader:
        if rn >= 5:
            if row[0] != '':
                prefix1 = row[0].capitalize()[0]
                category = row[0]
                print("\\end{tabular}\n\n")
                print("%%"+category)
                print("\\begin{tabular}{|m{2.5cm}|m{3cm}|m{1cm}|m{1cm}|p{8cm}|}")
                print("\\hline \\textbf{Type}&\\textbf{Metric}&\\textbf{ID}&\\textbf{Values}&\\textbf{Descritpion}\\\\ \\hline")
            if row[1] != '':
                prefix2 = ''
                rs = row[1].split()
                type = row[1]
                c = 0
                for w in rs:
                    prefix2 += w.capitalize()[0]
                    c += 1
                    if c == 2:
                        break
                nip = 0
            nip += 1
            print("\\textbf{"+row[1]+"}&"+row[2]+"&"+prefix1+prefix2+str(nip)+"&"+row[3]+"&"+row[4].replace("%", "\%")+"\\\\ \\hline")        
        rn += 1

print("\\end{tabular}")
